### ISSUE TITLE
Error loading std.curv

### ISSUE THREAD

**Issue by dfphil** [curv3d/curv#105]
Curv compiles without incident. When I run an example I get an error pointing to std.curv

~/src/curv% curv examples/shreks_donut.curv
ERROR: argument #1 of char: #'$' is not an integer, string, or list of these
at file "/usr/local/lib/curv/std.curv":
23| dol = char #'$';  // dollar sign character
               ^^^^
I am on a MacBook Pro running 10.15.7 and I use Home Brew to install all the dependencies. 
(This is my first bug report via GitHub; my apologies for the terseness.)

**Comment by doug-moen** [comment]
I introduced this bug earlier today when I changed an API. I updated std.curv to use the new API but forgot to push the changed file to github. Thanks for catching it.
