### ISSUE TITLE
Clean up curvc and makefile

### ISSUE THREAD

**Issue by zeeyang** [curv3d/curv#119]
Is it safe to remove `curvc` after `jcpu` export option? https://github.com/curv3d/curv/pull/115

**Comment by doug-moen** [comment]
Curvc is unmaintained code which IMO never worked correctly. I haven't tested it in a long time, so it is probably bit rotted. I am happy to remove curvc. The code remains in git, so it can be resurrected if somebody needs it again.

The original goal of curvc was to support communication between curv running on a server and a client running in a web browser, using JSON to encode the communication. The full protocol required encoding arbitrary Curv values in JSON, which never worked in a satisfactory way (functions and shapes never worked), and that capability has degraded as I've further extended the Curv type system, adding new kinds of values with no JSON equivalent.
