### ISSUE TITLE
Bad baground color after two rotation transformations

### ISSUE THREAD

**Issue by jasonrohrer** [curv3d/curv#157]
This occurs whenever ray_max_depth=inf, and thus became default behavior after 196f512572ef1bc92588f154e312fc729a752fef

It can also be reproduced in previous curv versions by setting 
```
-O ray_max_depth=inf
```

Sample code:
```
cube
>> rotate { angle: (-90*deg), axis: Y_axis }
>> rotate { angle: (-90*deg), axis: X_axis }
```
Note that this bug seems to be specific to 90 degrees as a rotation angle.

![Screenshot from 2021-12-10 11-30-24](https://user-images.githubusercontent.com/12563681/145608198-b0d5749e-394d-4e51-8199-3ef4d139001c.png)

**Comment by jasonrohrer** [comment]
Whoa, setting one of them to 45 produces a very odd result:

```
cube
>> rotate { angle: (-90*deg), axis: Y_axis }
>> rotate { angle: (-90*deg), axis: X_axis }
```

![Screenshot from 2021-12-10 11-33-22](https://user-images.githubusercontent.com/12563681/145608493-eab1c931-e126-4643-87e3-accb8c6d251b.png)

**Comment by lf94** [comment]
Doug is working on fixing this soon via constraining ray-max-depth to bounding box.

**Comment by doug-moen** [comment]
This only happens when you set ray_max_depth to infinity, which is now officially unsupported :-)
The default value is no longer infinity, it's 2000, so nobody will now see this behaviour by accident.
