### ISSUE TITLE
Error on Ubuntu  (22.04 LTS)

### ISSUE THREAD

**Issue by meleano** [curv3d/curv#162]
Here you have the output  my terminal output  after execute Make  (Error over class  tbb::split ):

CMake Warning at extern/openvdb/openvdb/openvdb/CMakeLists.txt:157 (message):
  Blosc support is disabled.  It is strongly recommended to enable blosc for
  optimal builds of OpenVDB and to support compatible serialization of other
  OpenVDB installations.

CMake Deprecation Warning at extern/googletest/googletest/CMakeLists.txt:48 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

In file included from /usr/include/tbb/parallel_reduce.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:18,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/usr/include/oneapi/tbb/parallel_reduce.h:379:57: error: reference to ‘split’ is ambiguous
  379 |     lambda_reduce_body( lambda_reduce_body& other, tbb::split )
      |                                                         ^~~~~
In file included from /usr/include/oneapi/tbb/partitioner.h:42,
                 from /usr/include/oneapi/tbb/parallel_for.h:27,
                 from /usr/include/tbb/parallel_for.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/usr/include/oneapi/tbb/detail/_range_common.h:36:7: note: candidates are: ‘class tbb::detail::d0::split’
   36 | class split {};
      |       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/Types.h:37,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Metadata.h:9,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/MetaMap.h:7,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:8,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/math/Coord.h:16:23: note:                 ‘class tbb::split’
   16 | namespace tbb { class split; } // forward declaration
      |                       ^~~~~
In file included from /usr/include/tbb/parallel_reduce.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:18,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/usr/include/oneapi/tbb/parallel_reduce.h:379:57: error: ‘tbb::split’ has not been declared
  379 |     lambda_reduce_body( lambda_reduce_body& other, tbb::split )
      |                                                         ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:194:38: error: reference to ‘split’ is ambiguous
  194 |         NodeRange(NodeRange& r, tbb::split):
      |                                      ^~~~~
In file included from /usr/include/oneapi/tbb/partitioner.h:42,
                 from /usr/include/oneapi/tbb/parallel_for.h:27,
                 from /usr/include/tbb/parallel_for.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/usr/include/oneapi/tbb/detail/_range_common.h:36:7: note: candidates are: ‘class tbb::detail::d0::split’
   36 | class split {};
      |       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/Types.h:37,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Metadata.h:9,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/MetaMap.h:7,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:8,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/math/Coord.h:16:23: note:                 ‘class tbb::split’
   16 | namespace tbb { class split; } // forward declaration
      |                       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:194:38: error: ‘tbb::split’ has not been declared
  194 |         NodeRange(NodeRange& r, tbb::split):
      |                                      ^~~~~
/home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:363:52: error: reference to ‘split’ is ambiguous
  363 |         NodeReducer(const NodeReducer& other, tbb::split)
      |                                                    ^~~~~
In file included from /usr/include/oneapi/tbb/partitioner.h:42,
                 from /usr/include/oneapi/tbb/parallel_for.h:27,
                 from /usr/include/tbb/parallel_for.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/usr/include/oneapi/tbb/detail/_range_common.h:36:7: note: candidates are: ‘class tbb::detail::d0::split’
   36 | class split {};
      |       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/Types.h:37,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Metadata.h:9,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/MetaMap.h:7,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:8,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/math/Coord.h:16:23: note:                 ‘class tbb::split’
   16 | namespace tbb { class split; } // forward declaration
      |                       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:363:52: error: ‘tbb::split’ has not been declared
  363 |         NodeReducer(const NodeReducer& other, tbb::split)
      |                                                    ^~~~~
/home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h: In constructor ‘openvdb::v8_1::tree::NodeList<NodeT>::NodeReducer<NodeOp, OpT>::NodeReducer(const openvdb::v8_1::tree::NodeList<NodeT>::NodeReducer<NodeOp, OpT>&, int)’:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:364:74: error: reference to ‘split’ is ambiguous
  364 |  : mNodeOpPtr(std::make_unique<NodeOp>(*(other.mNodeOp), tbb::split()))
      |                                                               ^~~~~

In file included from /usr/include/oneapi/tbb/partitioner.h:42,
                 from /usr/include/oneapi/tbb/parallel_for.h:27,
                 from /usr/include/tbb/parallel_for.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/usr/include/oneapi/tbb/detail/_range_common.h:36:7: note: candidates are: ‘class tbb::detail::d0::split’
   36 | class split {};
      |       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/Types.h:37,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Metadata.h:9,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/MetaMap.h:7,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:8,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/math/Coord.h:16:23: note:                 ‘class tbb::split’
   16 | namespace tbb { class split; } // forward declaration
      |                       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h: At global scope:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:766:54: error: reference to ‘split’ is ambiguous
  766 |     ReduceFilterOp(const ReduceFilterOp& other, tbb::split)
      |                                                      ^~~~~
In file included from /usr/include/oneapi/tbb/partitioner.h:42,
                 from /usr/include/oneapi/tbb/parallel_for.h:27,
                 from /usr/include/tbb/parallel_for.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/usr/include/oneapi/tbb/detail/_range_common.h:36:7: note: candidates are: ‘class tbb::detail::d0::split’
   36 | class split {};
      |       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/Types.h:37,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Metadata.h:9,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/MetaMap.h:7,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:8,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/math/Coord.h:16:23: note:                 ‘class tbb::split’
   16 | namespace tbb { class split; } // forward declaration
      |                       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:766:54: error: ‘tbb::split’ has not been declared
  766 |     ReduceFilterOp(const ReduceFilterOp& other, tbb::split)
      |                                                      ^~~~~
/home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h: In constructor ‘openvdb::v8_1::tree::ReduceFilterOp<OpT>::ReduceFilterOp(const openvdb::v8_1::tree::ReduceFilterOp<OpT>&, int)’:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:767:59: error: reference to ‘split’ is ambiguous
  767 |         : mOpPtr(std::make_unique<OpT>(*(other.mOp), tbb::split()))
      |                                                           ^~~~~
In file included from /usr/include/oneapi/tbb/partitioner.h:42,
                 from /usr/include/oneapi/tbb/parallel_for.h:27,
                 from /usr/include/tbb/parallel_for.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/usr/include/oneapi/tbb/detail/_range_common.h:36:7: note: candidates are: ‘class tbb::detail::d0::split’
   36 | class split {};
      |       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/Types.h:37,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Metadata.h:9,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/MetaMap.h:7,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:8,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/math/Coord.h:16:23: note:                 ‘class tbb::split’
   16 | namespace tbb { class split; } // forward declaration
      |                       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h: At global scope:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:51:56: error: reference to ‘split’ is ambiguous
   51 |     ActiveVoxelCountOp(const ActiveVoxelCountOp&, tbb::split) { }
      |                                                        ^~~~~
In file included from /usr/include/oneapi/tbb/partitioner.h:42,
                 from /usr/include/oneapi/tbb/parallel_for.h:27,
                 from /usr/include/tbb/parallel_for.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/usr/include/oneapi/tbb/detail/_range_common.h:36:7: note: candidates are: ‘class tbb::detail::d0::split’
   36 | class split {};
      |       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/Types.h:37,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Metadata.h:9,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/MetaMap.h:7,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:8,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/math/Coord.h:16:23: note:                 ‘class tbb::split’
   16 | namespace tbb { class split; } // forward declaration
      |                       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:51:56: error: ‘tbb::split’ has not been declared
   51 |     ActiveVoxelCountOp(const ActiveVoxelCountOp&, tbb::split) { }
      |                                                        ^~~~~
/home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:87:70: error: reference to ‘split’ is ambiguous
   87 | ActiveVoxelCountBBoxOp(const ActiveVoxelCountBBoxOp& other, tbb::split)
      |                                                                  ^~~~~

In file included from /usr/include/oneapi/tbb/partitioner.h:42,
                 from /usr/include/oneapi/tbb/parallel_for.h:27,
                 from /usr/include/tbb/parallel_for.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/usr/include/oneapi/tbb/detail/_range_common.h:36:7: note: candidates are: ‘class tbb::detail::d0::split’
   36 | class split {};
      |       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/Types.h:37,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Metadata.h:9,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/MetaMap.h:7,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:8,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/math/Coord.h:16:23: note:                 ‘class tbb::split’
   16 | namespace tbb { class split; } // forward declaration
      |                       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:87:70: error: ‘tbb::split’ has not been declared
   87 | ActiveVoxelCountBBoxOp(const ActiveVoxelCountBBoxOp& other, tbb::split)
      |                                                                  ^~~~~

/home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:169:40: error: reference to ‘split’ is ambiguous
  169 |     MemUsageOp(const MemUsageOp&, tbb::split) { }
      |                                        ^~~~~
In file included from /usr/include/oneapi/tbb/partitioner.h:42,
                 from /usr/include/oneapi/tbb/parallel_for.h:27,
                 from /usr/include/tbb/parallel_for.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/usr/include/oneapi/tbb/detail/_range_common.h:36:7: note: candidates are: ‘class tbb::detail::d0::split’
   36 | class split {};
      |       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/Types.h:37,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Metadata.h:9,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/MetaMap.h:7,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:8,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/math/Coord.h:16:23: note:                 ‘class tbb::split’
   16 | namespace tbb { class split; } // forward declaration
      |                       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:169:40: error: ‘tbb::split’ has not been declared
  169 |     MemUsageOp(const MemUsageOp&, tbb::split) { }
      |                                        ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:20,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tree/TreeIterator.h:1312:46: error: reference to ‘split’ is ambiguous
 1312 |     IteratorRange(IteratorRange& other, tbb::split):
      |                                              ^~~~~
In file included from /usr/include/oneapi/tbb/partitioner.h:42,
                 from /usr/include/oneapi/tbb/parallel_for.h:27,
                 from /usr/include/tbb/parallel_for.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/NodeManager.h:17,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tools/Count.h:15,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:13,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/usr/include/oneapi/tbb/detail/_range_common.h:36:7: note: candidates are: ‘class tbb::detail::d0::split’
   36 | class split {};
      |       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/Types.h:37,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Metadata.h:9,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/MetaMap.h:7,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:8,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/math/Coord.h:16:23: note:                 ‘class tbb::split’
   16 | namespace tbb { class split; } // forward declaration
      |                       ^~~~~
In file included from /home/mel/curv/extern/openvdb/openvdb/openvdb/tree/Tree.h:20,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.h:12,
                 from /home/mel/curv/extern/openvdb/openvdb/openvdb/Grid.cc:4:
/home/mel/curv/extern/openvdb/openvdb/openvdb/tree/TreeIterator.h:1312:46: error: ‘tbb::split’ has not been declared
 1312 |     IteratorRange(IteratorRange& other, tbb::split):
      |                                              ^~~~~
make[3]: *** [extern/openvdb/openvdb/openvdb/CMakeFiles/openvdb_static.dir/build.make:76: extern/openvdb/openvdb/openvdb/CMakeFiles/openvdb_static.dir/Grid.cc.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:645: extern/openvdb/openvdb/openvdb/CMakeFiles/openvdb_static.dir/all] Error 2
make[1]: *** [Makefile:136: all] Error 2
make: *** [Makefile:17: install] Error 2

**Comment by GraemeWilde** [comment]
Hi, I know this is a bit late, but I fixed this by updating the version of openvdb in the source files.

The steps I took are: 
```
cd curv/extern/openvdb
git checkout tags/v10.0.1
```
Then you need to go back to the root curv directory and edit the file CMakeLists.txt and find the lines
```
set(OpenVDB_MAJOR_VERSION 8)
set(OpenVDB_MINOR_VERSION 1)
set(OpenVDB_PATCH_VERSION 0)
```
And change them to:
```
set(OpenVDB_MAJOR_VERSION 10)
set(OpenVDB_MINOR_VERSION 0)
set(OpenVDB_PATCH_VERSION 1)
```

After that I got it to compile. 

As a side note to others: I also had to install libomp-dev to even get to the point where I got these errors, but I was building it on Windows 11 with WSL2 Ubuntu.

**Comment by lf94** [comment]
Thank you @GraemeWilde ! It seems OpenVDB is a big dependency and in some of Doug's notes he mentioned removing it. I'll pull in your fix :)

**Comment by GraemeWilde** [comment]
@lf94 You're welcome. I thought about submitting a pull request but I wasn't positive if this was actually the proper fix, and I didn't test it on anything other than my setup. 

Curv is a pretty interesting software and I'm happy I got it up and running.

**Comment by lf94** [comment]
You got me motivated to update all the dependencies and get it working with gcc 12 so this may take a bit!

**Comment by lf94** [comment]
Builds for Mac and Linux now work with GCC-12. Open new issues if you're still seeing build problems. Thanks!
