### ISSUE TITLE
Give me access to curv3d/libfive

### ISSUE THREAD

**Issue by lf94** [curv3d/curv#164]
I need access to that repository to push a branch `gcc-12` which has a single line fix to build libfive under gcc-12. It's the only blocker left for my PR 🙂

**Comment by doug-moen** [comment]
Since the libfive bug was fixed upstream in May 2022, we should stop using curv3d/libfive and just use libfive/libfive instead. The only reason I used curv3d/libfive before was to use a bug fix that wasn't yet accepted as a PR upstream.

**Comment by lf94** [comment]
Sounds good :)
