### ISSUE TITLE
Syntax Colouring

### ISSUE THREAD

**Issue by galex-713** [curv3d/curv#24]
I saw the idea of making a specific 3-pane GUI IDE just like libfive Studio or OpenSCAD. But a lot of people (at least me) already have their own editor/IDE that is neatly customized and can already edit (and possibly combine) several languages. libfive doesn’t require a such one since there is already scheme-mode and geiser under emacs (that does automatic autocompletion and autodoc in live using the repl).

But in emacs, as well as, I guess then, any other editor (gedit I guess), has absolutely no syntaxic coloring for curv and since the syntax is not strictly matching something already existing (or is it?) I then have all the text in only one (white) color, which can be quite boring and repulsive. Especially (I recall the time I saw people seeing their first languages in MS notepad…) for potential programming language newbies: I saw curv may be intended to try to attract more new artists than engineers, then it may (before to bring a standalone nice classic specific IDE) try to experiment with editing-capabilities so to make it more fun and attractive. And though emacs may be a bad example of newbie community, it is a good tool to experiment this kind of things and work for it may also be replicated on some more-newbie stuff such as gedit.

Sorry for maybe excessive verbosity, compared to this is.

**Comment by doug-moen** [comment]
Syntax colouring is now implemented for gedit.

**Comment by galex-713** [comment]
Where? with what colors and subset of grammar? what is colored? are all std lib constants? because that might interest me for an eventual emacs major mode

**Comment by doug-moen** [comment]
**What did you use as a resource?**
> I used this as a starting point: https://askubuntu.com/questions/55494/how-do-i-add-a-syntax-highlighter-format-to-gedit and followed the links.
> Then I looked at some other gedit language files, copied and pasted, and ran experiments to see what worked.

**With what subset of the grammar? What is coloured? Why is `_` coloured?**
> I did some research into syntax highlighting. I discovered a distinction between token colouring, where you use different colours for different token types in the lexical grammar of the language, vs semantic highlighting, as is found in KDevelop. Semantic highlighting requires a full IDE, which I will implement eventually. Token colouring is much easier, so I did that.
>
> So I assigned different colours to different token types. Comments are blue. String literals and numerals are pink. Keywords are red. Certain operator symbols are red.
>
> `_` is a keyword because it has a special meaning in pattern matching. It is the wildcard pattern, and means "match any pattern, but don't bind the value to an identifier". See https://github.com/doug-moen/curv/blob/master/docs/language/Patterns.rst

**are all std lib constants?**
> None of the std lib bindings have special colouring. That creates a maintenance burden (of updating the syntax colouring config whenever the std lib changes). Also, it's really a form of semantic highlighting, not just token colouring, and it's better if the IDE can colour identifiers based on true knowledge of what those identifiers are bound to in their lexical scope.

**Comment by doug-moen** [comment]
I cheated a bit in the current gedit syntax highlighter.

In Curv, you can write `${expression}` as an escape sequence inside a string literal. It will evaluate *expression*, convert the resulting value into a string if not already a string, then interpolate the result. To colour this correctly, I would need to write a parser for the entire language using recursive regular expressions, which is possible, but complicated, so I deferred it until later.

**Comment by s-ol** [comment]
@doug-moen since replxx is now implemented, maybe this should be renamed + reopened?

Is there an appropriately performant parser in the curv source at the moment that could be used for this, or should an alternate, 'leightweight' set of regex rules be implemented, e.g. [as in the replxx example](https://github.com/AmokHuginnsson/replxx/blob/master/examples/cxx-api.cxx#L72)?

**Comment by doug-moen** [comment]
Syntax colouring is now implemented in the REPL (by @s-ol), and in gedit (by me). We still need syntax colouring for emacs and vim (these are "help wanted" items).

We do not have a final colouring scheme. Here are some TODO items:
* REPL and gedit both use the same colour scheme.
* The colour scheme looks good with a black background, and also with a white background.
* The colour scheme is well designed and harmonious. It highlights important syntactic distinctions while avoiding visual clutter.

**Comment by s-ol** [comment]
I have never written a vim syntax file but since I use it a lot I might find out how to soon, unless there is someone here who has done that before.

**Comment by doug-moen** [comment]
It's hard to create a portable colour scheme for ANSI colours, since you
don't know what palette is installed or what the text/background colours are.
Some colours must be avoided, like bright yellow, which isn't legible against
a white background.

Solarized is a well designed standard 16-colour palette: https://ethanschoonover.com/solarized/

I'd like to design a syntax colour scheme for Solarized, which can be activated
if the user has Solarized installed. It will look better than our default portable
colour scheme.

**Comment by doug-moen** [comment]
Proposed enhancements for REPL syntax colouring:
* Syntax colouring for comments. Note that comments are prepended to each token: they exist in the range `Token::first_white_` to `Token::first_`. If there is a trailing comment, it is prepended to the `k_end` token.
* Lexical errors (bad tokens like `123abc`) are coloured bright red.

**Comment by doug-moen** [comment]
Those proposed REPL syntax colouring enhancements were implemented.
Since the original ideas were implemented, and the discussion is no longer active, I'm closing the issue.
