### ISSUE TITLE
curvc: --version support

### ISSUE THREAD

**Issue by sebastien** [curv3d/curv#65]
`curved` (web-based curv editor) currently detects the presence and correct version of `curv` by running `curv --version` and parsing the output (as well as the status code). However, this does not work with `curvc`, would it be possible to have a `--version` command line option that outputs a similar information as the main `curv` command?

**Comment by doug-moen** [comment]
Here is my change:
```
$ ./curvc --version
0.3-317-g571abfc-dirty
```
Good enough?

**Comment by sebastien** [comment]
That's perfect, I checked and it works!
