### ISSUE TITLE
curvc: return status != 0 only when there is a major problem

### ISSUE THREAD

**Issue by sebastien** [curv3d/curv#66]
Right now, `curvc` returns a `$STATUS=1` when the given file is not found. I suggest that it only returns a `STATUS=1` when there is an internal error, and the error is output on stderr in a non-JSON format. If the error is output on stdout in JSON format, the status code should be 0.

To put things in context, curved will consider the engine has failed if the status is != 0, but if there is an application-level error (syntax error, missing file, etc), it will be detected as part of the JSON payload returned by the compiler.

This is consistent with the common practice in HTTP web services where you can communicate errors through the JSON payload with an error field and still reply a `200 OK`. The process's 200 OK equivalent being the `$STATUS=0`.

**Comment by doug-moen** [comment]
fixed
