### ISSUE TITLE
all examples assert: (px != 0), function operator->, file /usr/local/include/boost/smart_ptr/intrusive_ptr.hpp

### ISSUE THREAD

**Issue by yurivict** [curv3d/curv#82]

**Comment by doug-moen** [comment]
This is apparently platform or compiler dependent. Please paste the output of `curv --version` to help me reproduce the problem.

**Comment by doug-moen** [comment]
never mind, I reproduced it.

**Comment by doug-moen** [comment]
Thanks for the bug report.
